apiVersion: apps/v1
kind: Deployment
metadata:
  name: stresstest2
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 5 
  minReadySeconds: 4
  selector:
    matchLabels:
      app: stresstest2
  template:
    metadata:
      name: stresstest2
      labels:
        app: stresstest2
    spec:
      nodeSelector:
        kubernetes.io/hostname: erkan3
      terminationGracePeriodSeconds: 2
      containers:
      - name: stresskopf
        image: jess/stress
        args:
        - --vm
        - "1"
        - --vm-bytes
        - "300m"
        - --vm-hang
        - "0"

        resources:
          requests:
            cpu: 10m
            memory: 400Mi
            ephemeral-storage: "10Mi"
          limits:
            cpu: 50m
            memory: 500Mi
            ephemeral-storage: "10Mi"
