apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwwloose
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 4
  minReadySeconds: 4
  selector:
    matchLabels:
      app: wwwloose
  template:
    metadata:
      name: wwwloose
      labels:
        app: wwwloose
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: image1
        image: erkules/nginxhostname:v1
