apiVersion: apps/v1
kind: Deployment
metadata:
  name: wwwscrict
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 6
  minReadySeconds: 4
  selector:
    matchLabels:
      app: wwwscrict
  template:
    metadata:
      name: wwwscrict
      labels:
        app: wwwscrict
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: image1
        image: erkules/nginxhostname:v1
        resources:
          requests:
            cpu: 10m
            memory: 20Mi
            ephemeral-storage: 10Mi
          limits:
            cpu: 10m
            memory: 20Mi
            ephemeral-storage: 10Mi
