apiVersion: apps/v1
kind: Deployment
metadata:
  name: showscheduler
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 4
  minReadySeconds: 4
  selector:
    matchLabels:
      app: showscheduler
  template:
    metadata:
      name: showscheduler
      labels:
        app: showscheduler
    spec:
      terminationGracePeriodSeconds: 2
      containers:
      - name: image1
        image: erkules/nginxhostname:v1
        resources:
          requests:
            memory: 500Mi
