apiVersion: apps/v1
kind: Deployment
metadata:
  name: stressunderrequest
spec:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  replicas: 3 
  minReadySeconds: 4
  selector:
    matchLabels:
      app: stressunderrequest
  template:
    metadata:
      name: stressunderrequest
      labels:
        app: stressunderrequest
    spec:
      nodeSelector:
        kubernetes.io/hostname: erkan2
      terminationGracePeriodSeconds: 2
      containers:
      - name: stressunderrequest
        image: jess/stress
        args:
        - --vm
        - "1"
        - --vm-bytes
        - "150m"
        - --vm-hang
        - "0"
        resources:
          requests:
            cpu: 10m
            memory: 200Mi
            ephemeral-storage: "10Mi"
          limits:
            cpu: 50m
            memory: 500Mi
            ephemeral-storage: "10Mi"
